version: "2"

run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G115  # Integer overflow conversions - handled where needed
        - G301  # Directory permissions (0o755)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: third_party/
      linters:
        - all
    - path: examples/
      linters:
        - all
