run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gosec:
    excludes:
      - G115
      - G301

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: third_party/
      linters:
        - all
    - path: examples/
      linters:
        - all
