// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/service/apko/apko_manager.proto

package apko

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the health status.
type ManagerHealthResponse_Status int32

const (
	ManagerHealthResponse_UNKNOWN     ManagerHealthResponse_Status = 0
	ManagerHealthResponse_SERVING     ManagerHealthResponse_Status = 1
	ManagerHealthResponse_NOT_SERVING ManagerHealthResponse_Status = 2
)

// Enum value maps for ManagerHealthResponse_Status.
var (
	ManagerHealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	ManagerHealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x ManagerHealthResponse_Status) Enum() *ManagerHealthResponse_Status {
	p := new(ManagerHealthResponse_Status)
	*p = x
	return p
}

func (x ManagerHealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagerHealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_service_apko_apko_manager_proto_enumTypes[0].Descriptor()
}

func (ManagerHealthResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_service_apko_apko_manager_proto_enumTypes[0]
}

func (x ManagerHealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagerHealthResponse_Status.Descriptor instead.
func (ManagerHealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{13, 0}
}

// RequestInstanceRequest specifies requirements for acquiring an apko instance.
type RequestInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the identifier for this build job (for logging/tracing).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// estimated_duration_ms is the estimated build duration in milliseconds.
	// Used for load balancing decisions.
	EstimatedDurationMs int64 `protobuf:"varint,2,opt,name=estimated_duration_ms,json=estimatedDurationMs,proto3" json:"estimated_duration_ms,omitempty"`
	// priority indicates the importance of this build (higher = more important).
	Priority      int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInstanceRequest) Reset() {
	*x = RequestInstanceRequest{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInstanceRequest) ProtoMessage() {}

func (x *RequestInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInstanceRequest.ProtoReflect.Descriptor instead.
func (*RequestInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RequestInstanceRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestInstanceRequest) GetEstimatedDurationMs() int64 {
	if x != nil {
		return x.EstimatedDurationMs
	}
	return 0
}

func (x *RequestInstanceRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// RequestInstanceResponse contains the acquired instance information.
type RequestInstanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance contains the acquired instance details.
	Instance      *InstanceInfo `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInstanceResponse) Reset() {
	*x = RequestInstanceResponse{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInstanceResponse) ProtoMessage() {}

func (x *RequestInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInstanceResponse.ProtoReflect.Descriptor instead.
func (*RequestInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RequestInstanceResponse) GetInstance() *InstanceInfo {
	if x != nil {
		return x.Instance
	}
	return nil
}

// InstanceInfo represents an acquired apko instance.
// Named InstanceInfo to avoid conflict with Go types.
type InstanceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for this instance.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// addr is the apko service gRPC address (e.g., "apko-server:9090").
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// max_concurrent is the maximum concurrent builds this instance supports.
	MaxConcurrent int32 `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	// acquired_at_unix is when this instance was acquired (Unix timestamp).
	AcquiredAtUnix int64 `protobuf:"varint,4,opt,name=acquired_at_unix,json=acquiredAtUnix,proto3" json:"acquired_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{2}
}

func (x *InstanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *InstanceInfo) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *InstanceInfo) GetAcquiredAtUnix() int64 {
	if x != nil {
		return x.AcquiredAtUnix
	}
	return 0
}

// ReleaseInstanceRequest returns an instance and records the build result.
type ReleaseInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id is the ID of the instance to release.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// result records the outcome of the build.
	Result        *BuildResultInfo `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseInstanceRequest) Reset() {
	*x = ReleaseInstanceRequest{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseInstanceRequest) ProtoMessage() {}

func (x *ReleaseInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseInstanceRequest.ProtoReflect.Descriptor instead.
func (*ReleaseInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ReleaseInstanceRequest) GetResult() *BuildResultInfo {
	if x != nil {
		return x.Result
	}
	return nil
}

// BuildResultInfo records the outcome of a build for tracking and circuit breaking.
// Named BuildResultInfo to avoid conflict with Go types.
type BuildResultInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the build completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// duration_ms is how long the build took in milliseconds.
	DurationMs int64 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// error is the error message if the build failed.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// cache_hit indicates whether the result was served from cache.
	CacheHit      bool `protobuf:"varint,4,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResultInfo) Reset() {
	*x = BuildResultInfo{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResultInfo) ProtoMessage() {}

func (x *BuildResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResultInfo.ProtoReflect.Descriptor instead.
func (*BuildResultInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{4}
}

func (x *BuildResultInfo) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildResultInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BuildResultInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildResultInfo) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

// ReleaseInstanceResponse is the response from releasing an instance.
type ReleaseInstanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// released indicates whether the instance was successfully released.
	Released      bool `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseInstanceResponse) Reset() {
	*x = ReleaseInstanceResponse{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseInstanceResponse) ProtoMessage() {}

func (x *ReleaseInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseInstanceResponse.ProtoReflect.Descriptor instead.
func (*ReleaseInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseInstanceResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

// GetManagerStatusRequest is a request for manager status.
type GetManagerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagerStatusRequest) Reset() {
	*x = GetManagerStatusRequest{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagerStatusRequest) ProtoMessage() {}

func (x *GetManagerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetManagerStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{6}
}

// GetManagerStatusResponse contains the current state of the manager.
type GetManagerStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status contains the manager status.
	Status        *ManagerStatusInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagerStatusResponse) Reset() {
	*x = GetManagerStatusResponse{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagerStatusResponse) ProtoMessage() {}

func (x *GetManagerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetManagerStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{7}
}

func (x *GetManagerStatusResponse) GetStatus() *ManagerStatusInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

// ManagerStatusInfo represents the current state of the manager for observability.
// Named ManagerStatusInfo to avoid conflict with Go types.
type ManagerStatusInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the manager implementation type (e.g., "static", "kubernetes").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// total_instances is the total number of apko instances available.
	TotalInstances int32 `protobuf:"varint,2,opt,name=total_instances,json=totalInstances,proto3" json:"total_instances,omitempty"`
	// total_capacity is the total concurrent build capacity across all instances.
	TotalCapacity int32 `protobuf:"varint,3,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	// active_builds is the total number of builds currently running.
	ActiveBuilds int32 `protobuf:"varint,4,opt,name=active_builds,json=activeBuilds,proto3" json:"active_builds,omitempty"`
	// instances contains status for each individual instance.
	Instances []*InstanceStatusInfo `protobuf:"bytes,5,rep,name=instances,proto3" json:"instances,omitempty"`
	// cache_hits is the total number of cache hits across all instances.
	CacheHits int64 `protobuf:"varint,6,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	// cache_misses is the total number of cache misses across all instances.
	CacheMisses   int64 `protobuf:"varint,7,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerStatusInfo) Reset() {
	*x = ManagerStatusInfo{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerStatusInfo) ProtoMessage() {}

func (x *ManagerStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerStatusInfo.ProtoReflect.Descriptor instead.
func (*ManagerStatusInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{8}
}

func (x *ManagerStatusInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ManagerStatusInfo) GetTotalInstances() int32 {
	if x != nil {
		return x.TotalInstances
	}
	return 0
}

func (x *ManagerStatusInfo) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *ManagerStatusInfo) GetActiveBuilds() int32 {
	if x != nil {
		return x.ActiveBuilds
	}
	return 0
}

func (x *ManagerStatusInfo) GetInstances() []*InstanceStatusInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ManagerStatusInfo) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *ManagerStatusInfo) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

// InstanceStatusInfo represents the current state of a single apko instance.
// Named InstanceStatusInfo to avoid conflict with Go types.
type InstanceStatusInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the instance identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// addr is the apko service gRPC address.
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// active_builds is the number of builds currently running on this instance.
	ActiveBuilds int32 `protobuf:"varint,3,opt,name=active_builds,json=activeBuilds,proto3" json:"active_builds,omitempty"`
	// max_concurrent is the maximum concurrent builds this instance supports.
	MaxConcurrent int32 `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	// circuit_open indicates if the circuit breaker is open (instance excluded).
	CircuitOpen bool `protobuf:"varint,5,opt,name=circuit_open,json=circuitOpen,proto3" json:"circuit_open,omitempty"`
	// failures is the number of consecutive failures.
	Failures int32 `protobuf:"varint,6,opt,name=failures,proto3" json:"failures,omitempty"`
	// last_failure_unix is the time of the last failure (Unix timestamp).
	LastFailureUnix int64 `protobuf:"varint,7,opt,name=last_failure_unix,json=lastFailureUnix,proto3" json:"last_failure_unix,omitempty"`
	// cache_hits is the number of cache hits on this instance.
	CacheHits int64 `protobuf:"varint,8,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	// cache_misses is the number of cache misses on this instance.
	CacheMisses   int64 `protobuf:"varint,9,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStatusInfo) Reset() {
	*x = InstanceStatusInfo{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatusInfo) ProtoMessage() {}

func (x *InstanceStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatusInfo.ProtoReflect.Descriptor instead.
func (*InstanceStatusInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{9}
}

func (x *InstanceStatusInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceStatusInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *InstanceStatusInfo) GetActiveBuilds() int32 {
	if x != nil {
		return x.ActiveBuilds
	}
	return 0
}

func (x *InstanceStatusInfo) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *InstanceStatusInfo) GetCircuitOpen() bool {
	if x != nil {
		return x.CircuitOpen
	}
	return false
}

func (x *InstanceStatusInfo) GetFailures() int32 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *InstanceStatusInfo) GetLastFailureUnix() int64 {
	if x != nil {
		return x.LastFailureUnix
	}
	return 0
}

func (x *InstanceStatusInfo) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *InstanceStatusInfo) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

// GetManagerCapacityRequest is a request for total capacity.
type GetManagerCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagerCapacityRequest) Reset() {
	*x = GetManagerCapacityRequest{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagerCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagerCapacityRequest) ProtoMessage() {}

func (x *GetManagerCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagerCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetManagerCapacityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{10}
}

// GetManagerCapacityResponse contains the total build capacity.
type GetManagerCapacityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_capacity is the total number of concurrent builds supported.
	TotalCapacity int32 `protobuf:"varint,1,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	// available_capacity is the current available capacity.
	AvailableCapacity int32 `protobuf:"varint,2,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetManagerCapacityResponse) Reset() {
	*x = GetManagerCapacityResponse{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagerCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagerCapacityResponse) ProtoMessage() {}

func (x *GetManagerCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagerCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetManagerCapacityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{11}
}

func (x *GetManagerCapacityResponse) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *GetManagerCapacityResponse) GetAvailableCapacity() int32 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

// ManagerHealthRequest is an empty request for health checks.
type ManagerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerHealthRequest) Reset() {
	*x = ManagerHealthRequest{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerHealthRequest) ProtoMessage() {}

func (x *ManagerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerHealthRequest.ProtoReflect.Descriptor instead.
func (*ManagerHealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{12}
}

// ManagerHealthResponse contains the health status of the service.
type ManagerHealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the current health status.
	Status ManagerHealthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=apko.manager.v1.ManagerHealthResponse_Status" json:"status,omitempty"`
	// manager_type is the type of manager being used.
	ManagerType string `protobuf:"bytes,2,opt,name=manager_type,json=managerType,proto3" json:"manager_type,omitempty"`
	// total_instances is the total number of apko instances.
	TotalInstances int32 `protobuf:"varint,3,opt,name=total_instances,json=totalInstances,proto3" json:"total_instances,omitempty"`
	// total_capacity is the total build capacity.
	TotalCapacity int32 `protobuf:"varint,4,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	// active_builds is the number of active builds.
	ActiveBuilds  int32 `protobuf:"varint,5,opt,name=active_builds,json=activeBuilds,proto3" json:"active_builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerHealthResponse) Reset() {
	*x = ManagerHealthResponse{}
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerHealthResponse) ProtoMessage() {}

func (x *ManagerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_apko_apko_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerHealthResponse.ProtoReflect.Descriptor instead.
func (*ManagerHealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_apko_apko_manager_proto_rawDescGZIP(), []int{13}
}

func (x *ManagerHealthResponse) GetStatus() ManagerHealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return ManagerHealthResponse_UNKNOWN
}

func (x *ManagerHealthResponse) GetManagerType() string {
	if x != nil {
		return x.ManagerType
	}
	return ""
}

func (x *ManagerHealthResponse) GetTotalInstances() int32 {
	if x != nil {
		return x.TotalInstances
	}
	return 0
}

func (x *ManagerHealthResponse) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *ManagerHealthResponse) GetActiveBuilds() int32 {
	if x != nil {
		return x.ActiveBuilds
	}
	return 0
}

var File_pkg_service_apko_apko_manager_proto protoreflect.FileDescriptor

const file_pkg_service_apko_apko_manager_proto_rawDesc = "" +
	"\n" +
	"#pkg/service/apko/apko_manager.proto\x12\x0fapko.manager.v1\"\x7f\n" +
	"\x16RequestInstanceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x122\n" +
	"\x15estimated_duration_ms\x18\x02 \x01(\x03R\x13estimatedDurationMs\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"T\n" +
	"\x17RequestInstanceResponse\x129\n" +
	"\binstance\x18\x01 \x01(\v2\x1d.apko.manager.v1.InstanceInfoR\binstance\"\x83\x01\n" +
	"\fInstanceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\x12(\n" +
	"\x10acquired_at_unix\x18\x04 \x01(\x03R\x0eacquiredAtUnix\"s\n" +
	"\x16ReleaseInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x128\n" +
	"\x06result\x18\x02 \x01(\v2 .apko.manager.v1.BuildResultInfoR\x06result\"\x7f\n" +
	"\x0fBuildResultInfo\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1b\n" +
	"\tcache_hit\x18\x04 \x01(\bR\bcacheHit\"5\n" +
	"\x17ReleaseInstanceResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\x19\n" +
	"\x17GetManagerStatusRequest\"V\n" +
	"\x18GetManagerStatusResponse\x12:\n" +
	"\x06status\x18\x01 \x01(\v2\".apko.manager.v1.ManagerStatusInfoR\x06status\"\xa1\x02\n" +
	"\x11ManagerStatusInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x0ftotal_instances\x18\x02 \x01(\x05R\x0etotalInstances\x12%\n" +
	"\x0etotal_capacity\x18\x03 \x01(\x05R\rtotalCapacity\x12#\n" +
	"\ractive_builds\x18\x04 \x01(\x05R\factiveBuilds\x12A\n" +
	"\tinstances\x18\x05 \x03(\v2#.apko.manager.v1.InstanceStatusInfoR\tinstances\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x06 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\a \x01(\x03R\vcacheMisses\"\xb1\x02\n" +
	"\x12InstanceStatusInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12#\n" +
	"\ractive_builds\x18\x03 \x01(\x05R\factiveBuilds\x12%\n" +
	"\x0emax_concurrent\x18\x04 \x01(\x05R\rmaxConcurrent\x12!\n" +
	"\fcircuit_open\x18\x05 \x01(\bR\vcircuitOpen\x12\x1a\n" +
	"\bfailures\x18\x06 \x01(\x05R\bfailures\x12*\n" +
	"\x11last_failure_unix\x18\a \x01(\x03R\x0flastFailureUnix\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\b \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\t \x01(\x03R\vcacheMisses\"\x1b\n" +
	"\x19GetManagerCapacityRequest\"r\n" +
	"\x1aGetManagerCapacityResponse\x12%\n" +
	"\x0etotal_capacity\x18\x01 \x01(\x05R\rtotalCapacity\x12-\n" +
	"\x12available_capacity\x18\x02 \x01(\x05R\x11availableCapacity\"\x16\n" +
	"\x14ManagerHealthRequest\"\xab\x02\n" +
	"\x15ManagerHealthResponse\x12E\n" +
	"\x06status\x18\x01 \x01(\x0e2-.apko.manager.v1.ManagerHealthResponse.StatusR\x06status\x12!\n" +
	"\fmanager_type\x18\x02 \x01(\tR\vmanagerType\x12'\n" +
	"\x0ftotal_instances\x18\x03 \x01(\x05R\x0etotalInstances\x12%\n" +
	"\x0etotal_capacity\x18\x04 \x01(\x05R\rtotalCapacity\x12#\n" +
	"\ractive_builds\x18\x05 \x01(\x05R\factiveBuilds\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x83\x04\n" +
	"\x12ApkoManagerService\x12d\n" +
	"\x0fRequestInstance\x12'.apko.manager.v1.RequestInstanceRequest\x1a(.apko.manager.v1.RequestInstanceResponse\x12d\n" +
	"\x0fReleaseInstance\x12'.apko.manager.v1.ReleaseInstanceRequest\x1a(.apko.manager.v1.ReleaseInstanceResponse\x12`\n" +
	"\tGetStatus\x12(.apko.manager.v1.GetManagerStatusRequest\x1a).apko.manager.v1.GetManagerStatusResponse\x12f\n" +
	"\vGetCapacity\x12*.apko.manager.v1.GetManagerCapacityRequest\x1a+.apko.manager.v1.GetManagerCapacityResponse\x12W\n" +
	"\x06Health\x12%.apko.manager.v1.ManagerHealthRequest\x1a&.apko.manager.v1.ManagerHealthResponseB.Z,github.com/dlorenc/melange2/pkg/service/apkob\x06proto3"

var (
	file_pkg_service_apko_apko_manager_proto_rawDescOnce sync.Once
	file_pkg_service_apko_apko_manager_proto_rawDescData []byte
)

func file_pkg_service_apko_apko_manager_proto_rawDescGZIP() []byte {
	file_pkg_service_apko_apko_manager_proto_rawDescOnce.Do(func() {
		file_pkg_service_apko_apko_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_service_apko_apko_manager_proto_rawDesc), len(file_pkg_service_apko_apko_manager_proto_rawDesc)))
	})
	return file_pkg_service_apko_apko_manager_proto_rawDescData
}

var file_pkg_service_apko_apko_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_service_apko_apko_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_service_apko_apko_manager_proto_goTypes = []any{
	(ManagerHealthResponse_Status)(0),  // 0: apko.manager.v1.ManagerHealthResponse.Status
	(*RequestInstanceRequest)(nil),     // 1: apko.manager.v1.RequestInstanceRequest
	(*RequestInstanceResponse)(nil),    // 2: apko.manager.v1.RequestInstanceResponse
	(*InstanceInfo)(nil),               // 3: apko.manager.v1.InstanceInfo
	(*ReleaseInstanceRequest)(nil),     // 4: apko.manager.v1.ReleaseInstanceRequest
	(*BuildResultInfo)(nil),            // 5: apko.manager.v1.BuildResultInfo
	(*ReleaseInstanceResponse)(nil),    // 6: apko.manager.v1.ReleaseInstanceResponse
	(*GetManagerStatusRequest)(nil),    // 7: apko.manager.v1.GetManagerStatusRequest
	(*GetManagerStatusResponse)(nil),   // 8: apko.manager.v1.GetManagerStatusResponse
	(*ManagerStatusInfo)(nil),          // 9: apko.manager.v1.ManagerStatusInfo
	(*InstanceStatusInfo)(nil),         // 10: apko.manager.v1.InstanceStatusInfo
	(*GetManagerCapacityRequest)(nil),  // 11: apko.manager.v1.GetManagerCapacityRequest
	(*GetManagerCapacityResponse)(nil), // 12: apko.manager.v1.GetManagerCapacityResponse
	(*ManagerHealthRequest)(nil),       // 13: apko.manager.v1.ManagerHealthRequest
	(*ManagerHealthResponse)(nil),      // 14: apko.manager.v1.ManagerHealthResponse
}
var file_pkg_service_apko_apko_manager_proto_depIdxs = []int32{
	3,  // 0: apko.manager.v1.RequestInstanceResponse.instance:type_name -> apko.manager.v1.InstanceInfo
	5,  // 1: apko.manager.v1.ReleaseInstanceRequest.result:type_name -> apko.manager.v1.BuildResultInfo
	9,  // 2: apko.manager.v1.GetManagerStatusResponse.status:type_name -> apko.manager.v1.ManagerStatusInfo
	10, // 3: apko.manager.v1.ManagerStatusInfo.instances:type_name -> apko.manager.v1.InstanceStatusInfo
	0,  // 4: apko.manager.v1.ManagerHealthResponse.status:type_name -> apko.manager.v1.ManagerHealthResponse.Status
	1,  // 5: apko.manager.v1.ApkoManagerService.RequestInstance:input_type -> apko.manager.v1.RequestInstanceRequest
	4,  // 6: apko.manager.v1.ApkoManagerService.ReleaseInstance:input_type -> apko.manager.v1.ReleaseInstanceRequest
	7,  // 7: apko.manager.v1.ApkoManagerService.GetStatus:input_type -> apko.manager.v1.GetManagerStatusRequest
	11, // 8: apko.manager.v1.ApkoManagerService.GetCapacity:input_type -> apko.manager.v1.GetManagerCapacityRequest
	13, // 9: apko.manager.v1.ApkoManagerService.Health:input_type -> apko.manager.v1.ManagerHealthRequest
	2,  // 10: apko.manager.v1.ApkoManagerService.RequestInstance:output_type -> apko.manager.v1.RequestInstanceResponse
	6,  // 11: apko.manager.v1.ApkoManagerService.ReleaseInstance:output_type -> apko.manager.v1.ReleaseInstanceResponse
	8,  // 12: apko.manager.v1.ApkoManagerService.GetStatus:output_type -> apko.manager.v1.GetManagerStatusResponse
	12, // 13: apko.manager.v1.ApkoManagerService.GetCapacity:output_type -> apko.manager.v1.GetManagerCapacityResponse
	14, // 14: apko.manager.v1.ApkoManagerService.Health:output_type -> apko.manager.v1.ManagerHealthResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_service_apko_apko_manager_proto_init() }
func file_pkg_service_apko_apko_manager_proto_init() {
	if File_pkg_service_apko_apko_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_service_apko_apko_manager_proto_rawDesc), len(file_pkg_service_apko_apko_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_service_apko_apko_manager_proto_goTypes,
		DependencyIndexes: file_pkg_service_apko_apko_manager_proto_depIdxs,
		EnumInfos:         file_pkg_service_apko_apko_manager_proto_enumTypes,
		MessageInfos:      file_pkg_service_apko_apko_manager_proto_msgTypes,
	}.Build()
	File_pkg_service_apko_apko_manager_proto = out.File
	file_pkg_service_apko_apko_manager_proto_goTypes = nil
	file_pkg_service_apko_apko_manager_proto_depIdxs = nil
}
