// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pkg/service/apko/apko_manager.proto

package apko

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApkoManagerService_RequestInstance_FullMethodName = "/apko.manager.v1.ApkoManagerService/RequestInstance"
	ApkoManagerService_ReleaseInstance_FullMethodName = "/apko.manager.v1.ApkoManagerService/ReleaseInstance"
	ApkoManagerService_GetStatus_FullMethodName       = "/apko.manager.v1.ApkoManagerService/GetStatus"
	ApkoManagerService_GetCapacity_FullMethodName     = "/apko.manager.v1.ApkoManagerService/GetCapacity"
	ApkoManagerService_Health_FullMethodName          = "/apko.manager.v1.ApkoManagerService/Health"
)

// ApkoManagerServiceClient is the client API for ApkoManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApkoManagerService provides apko instance management as a gRPC service.
// This enables the orchestrator to communicate with the Apko Manager
// as a separate microservice, allowing independent scaling and fault isolation.
//
// Phase 7 of microservices architecture: See issue #186.
type ApkoManagerServiceClient interface {
	// RequestInstance acquires an apko instance for the given build requirements.
	// The returned instance must be released when the build completes.
	RequestInstance(ctx context.Context, in *RequestInstanceRequest, opts ...grpc.CallOption) (*RequestInstanceResponse, error)
	// ReleaseInstance returns an instance to the manager and records the build result.
	// This must be called when a build completes (regardless of outcome).
	ReleaseInstance(ctx context.Context, in *ReleaseInstanceRequest, opts ...grpc.CallOption) (*ReleaseInstanceResponse, error)
	// GetStatus returns current state of all instances for observability.
	GetStatus(ctx context.Context, in *GetManagerStatusRequest, opts ...grpc.CallOption) (*GetManagerStatusResponse, error)
	// GetCapacity returns the total build capacity across all instances.
	GetCapacity(ctx context.Context, in *GetManagerCapacityRequest, opts ...grpc.CallOption) (*GetManagerCapacityResponse, error)
	// Health returns the health status of the service.
	Health(ctx context.Context, in *ManagerHealthRequest, opts ...grpc.CallOption) (*ManagerHealthResponse, error)
}

type apkoManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApkoManagerServiceClient(cc grpc.ClientConnInterface) ApkoManagerServiceClient {
	return &apkoManagerServiceClient{cc}
}

func (c *apkoManagerServiceClient) RequestInstance(ctx context.Context, in *RequestInstanceRequest, opts ...grpc.CallOption) (*RequestInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestInstanceResponse)
	err := c.cc.Invoke(ctx, ApkoManagerService_RequestInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apkoManagerServiceClient) ReleaseInstance(ctx context.Context, in *ReleaseInstanceRequest, opts ...grpc.CallOption) (*ReleaseInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseInstanceResponse)
	err := c.cc.Invoke(ctx, ApkoManagerService_ReleaseInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apkoManagerServiceClient) GetStatus(ctx context.Context, in *GetManagerStatusRequest, opts ...grpc.CallOption) (*GetManagerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagerStatusResponse)
	err := c.cc.Invoke(ctx, ApkoManagerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apkoManagerServiceClient) GetCapacity(ctx context.Context, in *GetManagerCapacityRequest, opts ...grpc.CallOption) (*GetManagerCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManagerCapacityResponse)
	err := c.cc.Invoke(ctx, ApkoManagerService_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apkoManagerServiceClient) Health(ctx context.Context, in *ManagerHealthRequest, opts ...grpc.CallOption) (*ManagerHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManagerHealthResponse)
	err := c.cc.Invoke(ctx, ApkoManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApkoManagerServiceServer is the server API for ApkoManagerService service.
// All implementations must embed UnimplementedApkoManagerServiceServer
// for forward compatibility.
//
// ApkoManagerService provides apko instance management as a gRPC service.
// This enables the orchestrator to communicate with the Apko Manager
// as a separate microservice, allowing independent scaling and fault isolation.
//
// Phase 7 of microservices architecture: See issue #186.
type ApkoManagerServiceServer interface {
	// RequestInstance acquires an apko instance for the given build requirements.
	// The returned instance must be released when the build completes.
	RequestInstance(context.Context, *RequestInstanceRequest) (*RequestInstanceResponse, error)
	// ReleaseInstance returns an instance to the manager and records the build result.
	// This must be called when a build completes (regardless of outcome).
	ReleaseInstance(context.Context, *ReleaseInstanceRequest) (*ReleaseInstanceResponse, error)
	// GetStatus returns current state of all instances for observability.
	GetStatus(context.Context, *GetManagerStatusRequest) (*GetManagerStatusResponse, error)
	// GetCapacity returns the total build capacity across all instances.
	GetCapacity(context.Context, *GetManagerCapacityRequest) (*GetManagerCapacityResponse, error)
	// Health returns the health status of the service.
	Health(context.Context, *ManagerHealthRequest) (*ManagerHealthResponse, error)
	mustEmbedUnimplementedApkoManagerServiceServer()
}

// UnimplementedApkoManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApkoManagerServiceServer struct{}

func (UnimplementedApkoManagerServiceServer) RequestInstance(context.Context, *RequestInstanceRequest) (*RequestInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestInstance not implemented")
}
func (UnimplementedApkoManagerServiceServer) ReleaseInstance(context.Context, *ReleaseInstanceRequest) (*ReleaseInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseInstance not implemented")
}
func (UnimplementedApkoManagerServiceServer) GetStatus(context.Context, *GetManagerStatusRequest) (*GetManagerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedApkoManagerServiceServer) GetCapacity(context.Context, *GetManagerCapacityRequest) (*GetManagerCapacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedApkoManagerServiceServer) Health(context.Context, *ManagerHealthRequest) (*ManagerHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedApkoManagerServiceServer) mustEmbedUnimplementedApkoManagerServiceServer() {}
func (UnimplementedApkoManagerServiceServer) testEmbeddedByValue()                            {}

// UnsafeApkoManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApkoManagerServiceServer will
// result in compilation errors.
type UnsafeApkoManagerServiceServer interface {
	mustEmbedUnimplementedApkoManagerServiceServer()
}

func RegisterApkoManagerServiceServer(s grpc.ServiceRegistrar, srv ApkoManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedApkoManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApkoManagerService_ServiceDesc, srv)
}

func _ApkoManagerService_RequestInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoManagerServiceServer).RequestInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoManagerService_RequestInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoManagerServiceServer).RequestInstance(ctx, req.(*RequestInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApkoManagerService_ReleaseInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoManagerServiceServer).ReleaseInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoManagerService_ReleaseInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoManagerServiceServer).ReleaseInstance(ctx, req.(*ReleaseInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApkoManagerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoManagerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoManagerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoManagerServiceServer).GetStatus(ctx, req.(*GetManagerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApkoManagerService_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManagerCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoManagerServiceServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoManagerService_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoManagerServiceServer).GetCapacity(ctx, req.(*GetManagerCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApkoManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApkoManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApkoManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApkoManagerServiceServer).Health(ctx, req.(*ManagerHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApkoManagerService_ServiceDesc is the grpc.ServiceDesc for ApkoManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApkoManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apko.manager.v1.ApkoManagerService",
	HandlerType: (*ApkoManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestInstance",
			Handler:    _ApkoManagerService_RequestInstance_Handler,
		},
		{
			MethodName: "ReleaseInstance",
			Handler:    _ApkoManagerService_ReleaseInstance_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ApkoManagerService_GetStatus_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _ApkoManagerService_GetCapacity_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ApkoManagerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/service/apko/apko_manager.proto",
}
