// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/service/buildkit/buildkit_manager.proto

package buildkit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the health status.
type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_service_buildkit_buildkit_manager_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_pkg_service_buildkit_buildkit_manager_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{16, 0}
}

// RequestWorkerRequest specifies requirements for acquiring a BuildKit worker.
type RequestWorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// arch is the target architecture (e.g., "x86_64", "aarch64").
	// Required.
	Arch string `protobuf:"bytes,1,opt,name=arch,proto3" json:"arch,omitempty"`
	// job_id is the identifier for this build job (for logging/tracing).
	JobId string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// selector is a label selector for filtering backends.
	// All specified labels must match.
	Selector map[string]string `protobuf:"bytes,3,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// resources specifies estimated resource requirements for the build.
	Resources *ResourceRequirementsInfo `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	// priority indicates the importance of this build (higher = more important).
	Priority      int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWorkerRequest) Reset() {
	*x = RequestWorkerRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkerRequest) ProtoMessage() {}

func (x *RequestWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkerRequest.ProtoReflect.Descriptor instead.
func (*RequestWorkerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWorkerRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RequestWorkerRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestWorkerRequest) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *RequestWorkerRequest) GetResources() *ResourceRequirementsInfo {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RequestWorkerRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ResourceRequirementsInfo specifies estimated resource needs for a build.
// Named ResourceRequirementsInfo to avoid conflict with the Go ResourceRequirements type.
type ResourceRequirementsInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// memory_mb is the estimated memory requirement in megabytes.
	MemoryMb int64 `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// cpu_cores is the estimated CPU requirement in cores.
	CpuCores float64 `protobuf:"fixed64,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// disk_gb is the estimated disk requirement in gigabytes.
	DiskGb int64 `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	// timeout_seconds is the maximum duration for the build in seconds.
	TimeoutSeconds int64 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceRequirementsInfo) Reset() {
	*x = ResourceRequirementsInfo{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirementsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirementsInfo) ProtoMessage() {}

func (x *ResourceRequirementsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirementsInfo.ProtoReflect.Descriptor instead.
func (*ResourceRequirementsInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRequirementsInfo) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequirementsInfo) GetCpuCores() float64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceRequirementsInfo) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *ResourceRequirementsInfo) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// RequestWorkerResponse contains the acquired worker information.
type RequestWorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker contains the acquired worker details.
	Worker        *WorkerInfo `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWorkerResponse) Reset() {
	*x = RequestWorkerResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkerResponse) ProtoMessage() {}

func (x *RequestWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkerResponse.ProtoReflect.Descriptor instead.
func (*RequestWorkerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{2}
}

func (x *RequestWorkerResponse) GetWorker() *WorkerInfo {
	if x != nil {
		return x.Worker
	}
	return nil
}

// WorkerInfo represents an acquired BuildKit worker.
// Named WorkerInfo to avoid conflict with the Go Worker type in manager.go.
type WorkerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a unique identifier for this worker instance.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// addr is the BuildKit daemon address (e.g., "tcp://buildkit:1234").
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// arch is the architecture this worker supports.
	Arch string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	// labels are arbitrary key-value pairs for the worker.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// acquired_at_unix is when this worker was acquired (Unix timestamp).
	AcquiredAtUnix int64 `protobuf:"varint,5,opt,name=acquired_at_unix,json=acquiredAtUnix,proto3" json:"acquired_at_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *WorkerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *WorkerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkerInfo) GetAcquiredAtUnix() int64 {
	if x != nil {
		return x.AcquiredAtUnix
	}
	return 0
}

// ReleaseWorkerRequest returns a worker and records the build result.
type ReleaseWorkerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// worker_id is the ID of the worker to release.
	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// result records the outcome of the build.
	Result        *BuildResultInfo `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseWorkerRequest) Reset() {
	*x = ReleaseWorkerRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseWorkerRequest) ProtoMessage() {}

func (x *ReleaseWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseWorkerRequest.ProtoReflect.Descriptor instead.
func (*ReleaseWorkerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReleaseWorkerRequest) GetResult() *BuildResultInfo {
	if x != nil {
		return x.Result
	}
	return nil
}

// BuildResultInfo records the outcome of a build for tracking and circuit breaking.
// Named BuildResultInfo to avoid conflict with the Go BuildResult type in manager.go.
type BuildResultInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the build completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// duration_ms is how long the build took in milliseconds.
	DurationMs int64 `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// error is the error message if the build failed.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResultInfo) Reset() {
	*x = BuildResultInfo{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResultInfo) ProtoMessage() {}

func (x *BuildResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResultInfo.ProtoReflect.Descriptor instead.
func (*BuildResultInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{5}
}

func (x *BuildResultInfo) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildResultInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BuildResultInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReleaseWorkerResponse is the response from releasing a worker.
type ReleaseWorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// released indicates whether the worker was successfully released.
	Released      bool `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseWorkerResponse) Reset() {
	*x = ReleaseWorkerResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseWorkerResponse) ProtoMessage() {}

func (x *ReleaseWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseWorkerResponse.ProtoReflect.Descriptor instead.
func (*ReleaseWorkerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseWorkerResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

// GetStatusRequest is a request for manager status.
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{7}
}

// GetStatusResponse contains the current state of the manager.
type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status contains the manager status.
	Status        *ManagerStatusInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusResponse) GetStatus() *ManagerStatusInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

// ManagerStatusInfo represents the current state of the manager for observability.
// Named ManagerStatusInfo to avoid conflict with the Go ManagerStatus type in manager.go.
type ManagerStatusInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the manager implementation type (e.g., "static", "kubernetes").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// total_workers is the total number of workers available.
	TotalWorkers int32 `protobuf:"varint,2,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	// available_workers is the number of workers currently available.
	AvailableWorkers int32 `protobuf:"varint,3,opt,name=available_workers,json=availableWorkers,proto3" json:"available_workers,omitempty"`
	// active_jobs is the total number of jobs currently running.
	ActiveJobs int32 `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	// workers contains status for each individual worker.
	Workers       []*WorkerStatusInfo `protobuf:"bytes,5,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerStatusInfo) Reset() {
	*x = ManagerStatusInfo{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerStatusInfo) ProtoMessage() {}

func (x *ManagerStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerStatusInfo.ProtoReflect.Descriptor instead.
func (*ManagerStatusInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{9}
}

func (x *ManagerStatusInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ManagerStatusInfo) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *ManagerStatusInfo) GetAvailableWorkers() int32 {
	if x != nil {
		return x.AvailableWorkers
	}
	return 0
}

func (x *ManagerStatusInfo) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *ManagerStatusInfo) GetWorkers() []*WorkerStatusInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

// WorkerStatusInfo represents the current state of a single worker.
// Named WorkerStatusInfo to avoid conflict with the Go WorkerStatus type in manager.go.
type WorkerStatusInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the worker identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// addr is the BuildKit daemon address.
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// arch is the worker's architecture.
	Arch string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	// labels are the worker's labels.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// active_jobs is the number of jobs currently running on this worker.
	ActiveJobs int32 `protobuf:"varint,5,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	// max_jobs is the maximum concurrent jobs this worker can handle.
	MaxJobs int32 `protobuf:"varint,6,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`
	// circuit_open indicates if the circuit breaker is open (worker excluded).
	CircuitOpen bool `protobuf:"varint,7,opt,name=circuit_open,json=circuitOpen,proto3" json:"circuit_open,omitempty"`
	// failures is the number of consecutive failures.
	Failures int32 `protobuf:"varint,8,opt,name=failures,proto3" json:"failures,omitempty"`
	// last_failure_unix is the time of the last failure (Unix timestamp).
	LastFailureUnix int64 `protobuf:"varint,9,opt,name=last_failure_unix,json=lastFailureUnix,proto3" json:"last_failure_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerStatusInfo) Reset() {
	*x = WorkerStatusInfo{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatusInfo) ProtoMessage() {}

func (x *WorkerStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatusInfo.ProtoReflect.Descriptor instead.
func (*WorkerStatusInfo) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerStatusInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerStatusInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *WorkerStatusInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *WorkerStatusInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkerStatusInfo) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerStatusInfo) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *WorkerStatusInfo) GetCircuitOpen() bool {
	if x != nil {
		return x.CircuitOpen
	}
	return false
}

func (x *WorkerStatusInfo) GetFailures() int32 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *WorkerStatusInfo) GetLastFailureUnix() int64 {
	if x != nil {
		return x.LastFailureUnix
	}
	return 0
}

// GetCapacityRequest is a request for total capacity.
type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{11}
}

// GetCapacityResponse contains the total job capacity.
type GetCapacityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_capacity is the total number of concurrent jobs supported.
	TotalCapacity int32 `protobuf:"varint,1,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{12}
}

func (x *GetCapacityResponse) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

// GetArchitecturesRequest is a request for supported architectures.
type GetArchitecturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArchitecturesRequest) Reset() {
	*x = GetArchitecturesRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchitecturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchitecturesRequest) ProtoMessage() {}

func (x *GetArchitecturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchitecturesRequest.ProtoReflect.Descriptor instead.
func (*GetArchitecturesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{13}
}

// GetArchitecturesResponse contains the supported architectures.
type GetArchitecturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// architectures is the list of supported architectures.
	Architectures []string `protobuf:"bytes,1,rep,name=architectures,proto3" json:"architectures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArchitecturesResponse) Reset() {
	*x = GetArchitecturesResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArchitecturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArchitecturesResponse) ProtoMessage() {}

func (x *GetArchitecturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArchitecturesResponse.ProtoReflect.Descriptor instead.
func (*GetArchitecturesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{14}
}

func (x *GetArchitecturesResponse) GetArchitectures() []string {
	if x != nil {
		return x.Architectures
	}
	return nil
}

// HealthRequest is an empty request for health checks.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{15}
}

// HealthResponse contains the health status of the service.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the current health status.
	Status HealthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=buildkit.manager.v1.HealthResponse_Status" json:"status,omitempty"`
	// manager_type is the type of manager being used.
	ManagerType string `protobuf:"bytes,2,opt,name=manager_type,json=managerType,proto3" json:"manager_type,omitempty"`
	// total_workers is the total number of workers.
	TotalWorkers int32 `protobuf:"varint,3,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	// available_workers is the number of available workers.
	AvailableWorkers int32 `protobuf:"varint,4,opt,name=available_workers,json=availableWorkers,proto3" json:"available_workers,omitempty"`
	// active_jobs is the number of active jobs.
	ActiveJobs    int32 `protobuf:"varint,5,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_service_buildkit_buildkit_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP(), []int{16}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetManagerType() string {
	if x != nil {
		return x.ManagerType
	}
	return ""
}

func (x *HealthResponse) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *HealthResponse) GetAvailableWorkers() int32 {
	if x != nil {
		return x.AvailableWorkers
	}
	return 0
}

func (x *HealthResponse) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

var File_pkg_service_buildkit_buildkit_manager_proto protoreflect.FileDescriptor

const file_pkg_service_buildkit_buildkit_manager_proto_rawDesc = "" +
	"\n" +
	"+pkg/service/buildkit/buildkit_manager.proto\x12\x13buildkit.manager.v1\"\xbc\x02\n" +
	"\x14RequestWorkerRequest\x12\x12\n" +
	"\x04arch\x18\x01 \x01(\tR\x04arch\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12S\n" +
	"\bselector\x18\x03 \x03(\v27.buildkit.manager.v1.RequestWorkerRequest.SelectorEntryR\bselector\x12K\n" +
	"\tresources\x18\x04 \x01(\v2-.buildkit.manager.v1.ResourceRequirementsInfoR\tresources\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x18ResourceRequirementsInfo\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x03R\bmemoryMb\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x01R\bcpuCores\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x03R\x06diskGb\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\"P\n" +
	"\x15RequestWorkerResponse\x127\n" +
	"\x06worker\x18\x01 \x01(\v2\x1f.buildkit.manager.v1.WorkerInfoR\x06worker\"\xee\x01\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.buildkit.manager.v1.WorkerInfo.LabelsEntryR\x06labels\x12(\n" +
	"\x10acquired_at_unix\x18\x05 \x01(\x03R\x0eacquiredAtUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x14ReleaseWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12<\n" +
	"\x06result\x18\x02 \x01(\v2$.buildkit.manager.v1.BuildResultInfoR\x06result\"b\n" +
	"\x0fBuildResultInfo\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"3\n" +
	"\x15ReleaseWorkerResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"\x12\n" +
	"\x10GetStatusRequest\"S\n" +
	"\x11GetStatusResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\v2&.buildkit.manager.v1.ManagerStatusInfoR\x06status\"\xdb\x01\n" +
	"\x11ManagerStatusInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rtotal_workers\x18\x02 \x01(\x05R\ftotalWorkers\x12+\n" +
	"\x11available_workers\x18\x03 \x01(\x05R\x10availableWorkers\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x05R\n" +
	"activeJobs\x12?\n" +
	"\aworkers\x18\x05 \x03(\v2%.buildkit.manager.v1.WorkerStatusInfoR\aworkers\"\xf7\x02\n" +
	"\x10WorkerStatusInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12I\n" +
	"\x06labels\x18\x04 \x03(\v21.buildkit.manager.v1.WorkerStatusInfo.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vactive_jobs\x18\x05 \x01(\x05R\n" +
	"activeJobs\x12\x19\n" +
	"\bmax_jobs\x18\x06 \x01(\x05R\amaxJobs\x12!\n" +
	"\fcircuit_open\x18\a \x01(\bR\vcircuitOpen\x12\x1a\n" +
	"\bfailures\x18\b \x01(\x05R\bfailures\x12*\n" +
	"\x11last_failure_unix\x18\t \x01(\x03R\x0flastFailureUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12GetCapacityRequest\"<\n" +
	"\x13GetCapacityResponse\x12%\n" +
	"\x0etotal_capacity\x18\x01 \x01(\x05R\rtotalCapacity\"\x19\n" +
	"\x17GetArchitecturesRequest\"@\n" +
	"\x18GetArchitecturesResponse\x12$\n" +
	"\rarchitectures\x18\x01 \x03(\tR\rarchitectures\"\x0f\n" +
	"\rHealthRequest\"\x9f\x02\n" +
	"\x0eHealthResponse\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.buildkit.manager.v1.HealthResponse.StatusR\x06status\x12!\n" +
	"\fmanager_type\x18\x02 \x01(\tR\vmanagerType\x12#\n" +
	"\rtotal_workers\x18\x03 \x01(\x05R\ftotalWorkers\x12+\n" +
	"\x11available_workers\x18\x04 \x01(\x05R\x10availableWorkers\x12\x1f\n" +
	"\vactive_jobs\x18\x05 \x01(\x05R\n" +
	"activeJobs\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xea\x04\n" +
	"\x16BuildKitManagerService\x12f\n" +
	"\rRequestWorker\x12).buildkit.manager.v1.RequestWorkerRequest\x1a*.buildkit.manager.v1.RequestWorkerResponse\x12f\n" +
	"\rReleaseWorker\x12).buildkit.manager.v1.ReleaseWorkerRequest\x1a*.buildkit.manager.v1.ReleaseWorkerResponse\x12Z\n" +
	"\tGetStatus\x12%.buildkit.manager.v1.GetStatusRequest\x1a&.buildkit.manager.v1.GetStatusResponse\x12`\n" +
	"\vGetCapacity\x12'.buildkit.manager.v1.GetCapacityRequest\x1a(.buildkit.manager.v1.GetCapacityResponse\x12o\n" +
	"\x10GetArchitectures\x12,.buildkit.manager.v1.GetArchitecturesRequest\x1a-.buildkit.manager.v1.GetArchitecturesResponse\x12Q\n" +
	"\x06Health\x12\".buildkit.manager.v1.HealthRequest\x1a#.buildkit.manager.v1.HealthResponseB2Z0github.com/dlorenc/melange2/pkg/service/buildkitb\x06proto3"

var (
	file_pkg_service_buildkit_buildkit_manager_proto_rawDescOnce sync.Once
	file_pkg_service_buildkit_buildkit_manager_proto_rawDescData []byte
)

func file_pkg_service_buildkit_buildkit_manager_proto_rawDescGZIP() []byte {
	file_pkg_service_buildkit_buildkit_manager_proto_rawDescOnce.Do(func() {
		file_pkg_service_buildkit_buildkit_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_service_buildkit_buildkit_manager_proto_rawDesc), len(file_pkg_service_buildkit_buildkit_manager_proto_rawDesc)))
	})
	return file_pkg_service_buildkit_buildkit_manager_proto_rawDescData
}

var file_pkg_service_buildkit_buildkit_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_service_buildkit_buildkit_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_service_buildkit_buildkit_manager_proto_goTypes = []any{
	(HealthResponse_Status)(0),       // 0: buildkit.manager.v1.HealthResponse.Status
	(*RequestWorkerRequest)(nil),     // 1: buildkit.manager.v1.RequestWorkerRequest
	(*ResourceRequirementsInfo)(nil), // 2: buildkit.manager.v1.ResourceRequirementsInfo
	(*RequestWorkerResponse)(nil),    // 3: buildkit.manager.v1.RequestWorkerResponse
	(*WorkerInfo)(nil),               // 4: buildkit.manager.v1.WorkerInfo
	(*ReleaseWorkerRequest)(nil),     // 5: buildkit.manager.v1.ReleaseWorkerRequest
	(*BuildResultInfo)(nil),          // 6: buildkit.manager.v1.BuildResultInfo
	(*ReleaseWorkerResponse)(nil),    // 7: buildkit.manager.v1.ReleaseWorkerResponse
	(*GetStatusRequest)(nil),         // 8: buildkit.manager.v1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 9: buildkit.manager.v1.GetStatusResponse
	(*ManagerStatusInfo)(nil),        // 10: buildkit.manager.v1.ManagerStatusInfo
	(*WorkerStatusInfo)(nil),         // 11: buildkit.manager.v1.WorkerStatusInfo
	(*GetCapacityRequest)(nil),       // 12: buildkit.manager.v1.GetCapacityRequest
	(*GetCapacityResponse)(nil),      // 13: buildkit.manager.v1.GetCapacityResponse
	(*GetArchitecturesRequest)(nil),  // 14: buildkit.manager.v1.GetArchitecturesRequest
	(*GetArchitecturesResponse)(nil), // 15: buildkit.manager.v1.GetArchitecturesResponse
	(*HealthRequest)(nil),            // 16: buildkit.manager.v1.HealthRequest
	(*HealthResponse)(nil),           // 17: buildkit.manager.v1.HealthResponse
	nil,                              // 18: buildkit.manager.v1.RequestWorkerRequest.SelectorEntry
	nil,                              // 19: buildkit.manager.v1.WorkerInfo.LabelsEntry
	nil,                              // 20: buildkit.manager.v1.WorkerStatusInfo.LabelsEntry
}
var file_pkg_service_buildkit_buildkit_manager_proto_depIdxs = []int32{
	18, // 0: buildkit.manager.v1.RequestWorkerRequest.selector:type_name -> buildkit.manager.v1.RequestWorkerRequest.SelectorEntry
	2,  // 1: buildkit.manager.v1.RequestWorkerRequest.resources:type_name -> buildkit.manager.v1.ResourceRequirementsInfo
	4,  // 2: buildkit.manager.v1.RequestWorkerResponse.worker:type_name -> buildkit.manager.v1.WorkerInfo
	19, // 3: buildkit.manager.v1.WorkerInfo.labels:type_name -> buildkit.manager.v1.WorkerInfo.LabelsEntry
	6,  // 4: buildkit.manager.v1.ReleaseWorkerRequest.result:type_name -> buildkit.manager.v1.BuildResultInfo
	10, // 5: buildkit.manager.v1.GetStatusResponse.status:type_name -> buildkit.manager.v1.ManagerStatusInfo
	11, // 6: buildkit.manager.v1.ManagerStatusInfo.workers:type_name -> buildkit.manager.v1.WorkerStatusInfo
	20, // 7: buildkit.manager.v1.WorkerStatusInfo.labels:type_name -> buildkit.manager.v1.WorkerStatusInfo.LabelsEntry
	0,  // 8: buildkit.manager.v1.HealthResponse.status:type_name -> buildkit.manager.v1.HealthResponse.Status
	1,  // 9: buildkit.manager.v1.BuildKitManagerService.RequestWorker:input_type -> buildkit.manager.v1.RequestWorkerRequest
	5,  // 10: buildkit.manager.v1.BuildKitManagerService.ReleaseWorker:input_type -> buildkit.manager.v1.ReleaseWorkerRequest
	8,  // 11: buildkit.manager.v1.BuildKitManagerService.GetStatus:input_type -> buildkit.manager.v1.GetStatusRequest
	12, // 12: buildkit.manager.v1.BuildKitManagerService.GetCapacity:input_type -> buildkit.manager.v1.GetCapacityRequest
	14, // 13: buildkit.manager.v1.BuildKitManagerService.GetArchitectures:input_type -> buildkit.manager.v1.GetArchitecturesRequest
	16, // 14: buildkit.manager.v1.BuildKitManagerService.Health:input_type -> buildkit.manager.v1.HealthRequest
	3,  // 15: buildkit.manager.v1.BuildKitManagerService.RequestWorker:output_type -> buildkit.manager.v1.RequestWorkerResponse
	7,  // 16: buildkit.manager.v1.BuildKitManagerService.ReleaseWorker:output_type -> buildkit.manager.v1.ReleaseWorkerResponse
	9,  // 17: buildkit.manager.v1.BuildKitManagerService.GetStatus:output_type -> buildkit.manager.v1.GetStatusResponse
	13, // 18: buildkit.manager.v1.BuildKitManagerService.GetCapacity:output_type -> buildkit.manager.v1.GetCapacityResponse
	15, // 19: buildkit.manager.v1.BuildKitManagerService.GetArchitectures:output_type -> buildkit.manager.v1.GetArchitecturesResponse
	17, // 20: buildkit.manager.v1.BuildKitManagerService.Health:output_type -> buildkit.manager.v1.HealthResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_service_buildkit_buildkit_manager_proto_init() }
func file_pkg_service_buildkit_buildkit_manager_proto_init() {
	if File_pkg_service_buildkit_buildkit_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_service_buildkit_buildkit_manager_proto_rawDesc), len(file_pkg_service_buildkit_buildkit_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_service_buildkit_buildkit_manager_proto_goTypes,
		DependencyIndexes: file_pkg_service_buildkit_buildkit_manager_proto_depIdxs,
		EnumInfos:         file_pkg_service_buildkit_buildkit_manager_proto_enumTypes,
		MessageInfos:      file_pkg_service_buildkit_buildkit_manager_proto_msgTypes,
	}.Build()
	File_pkg_service_buildkit_buildkit_manager_proto = out.File
	file_pkg_service_buildkit_buildkit_manager_proto_goTypes = nil
	file_pkg_service_buildkit_buildkit_manager_proto_depIdxs = nil
}
