// Copyright 2024 Chainguard, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pkg/service/buildkit/buildkit_manager.proto

package buildkit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildKitManagerService_RequestWorker_FullMethodName    = "/buildkit.manager.v1.BuildKitManagerService/RequestWorker"
	BuildKitManagerService_ReleaseWorker_FullMethodName    = "/buildkit.manager.v1.BuildKitManagerService/ReleaseWorker"
	BuildKitManagerService_GetStatus_FullMethodName        = "/buildkit.manager.v1.BuildKitManagerService/GetStatus"
	BuildKitManagerService_GetCapacity_FullMethodName      = "/buildkit.manager.v1.BuildKitManagerService/GetCapacity"
	BuildKitManagerService_GetArchitectures_FullMethodName = "/buildkit.manager.v1.BuildKitManagerService/GetArchitectures"
	BuildKitManagerService_Health_FullMethodName           = "/buildkit.manager.v1.BuildKitManagerService/Health"
)

// BuildKitManagerServiceClient is the client API for BuildKitManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BuildKitManagerService provides BuildKit worker management as a gRPC service.
// This enables the orchestrator to communicate with the BuildKit Manager
// as a separate microservice, allowing independent scaling and fault isolation.
//
// Phase 6 of microservices architecture: See issue #186.
type BuildKitManagerServiceClient interface {
	// RequestWorker acquires a BuildKit worker for the given build requirements.
	// The returned worker must be released when the build completes.
	RequestWorker(ctx context.Context, in *RequestWorkerRequest, opts ...grpc.CallOption) (*RequestWorkerResponse, error)
	// ReleaseWorker returns a worker to the manager and records the build result.
	// This must be called when a build completes (regardless of outcome).
	ReleaseWorker(ctx context.Context, in *ReleaseWorkerRequest, opts ...grpc.CallOption) (*ReleaseWorkerResponse, error)
	// GetStatus returns current state of all workers for observability.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetCapacity returns the total job capacity across all backends.
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error)
	// GetArchitectures returns a list of supported architectures.
	GetArchitectures(ctx context.Context, in *GetArchitecturesRequest, opts ...grpc.CallOption) (*GetArchitecturesResponse, error)
	// Health returns the health status of the service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type buildKitManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildKitManagerServiceClient(cc grpc.ClientConnInterface) BuildKitManagerServiceClient {
	return &buildKitManagerServiceClient{cc}
}

func (c *buildKitManagerServiceClient) RequestWorker(ctx context.Context, in *RequestWorkerRequest, opts ...grpc.CallOption) (*RequestWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestWorkerResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_RequestWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildKitManagerServiceClient) ReleaseWorker(ctx context.Context, in *ReleaseWorkerRequest, opts ...grpc.CallOption) (*ReleaseWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseWorkerResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_ReleaseWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildKitManagerServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildKitManagerServiceClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapacityResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildKitManagerServiceClient) GetArchitectures(ctx context.Context, in *GetArchitecturesRequest, opts ...grpc.CallOption) (*GetArchitecturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchitecturesResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_GetArchitectures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildKitManagerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BuildKitManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildKitManagerServiceServer is the server API for BuildKitManagerService service.
// All implementations must embed UnimplementedBuildKitManagerServiceServer
// for forward compatibility.
//
// BuildKitManagerService provides BuildKit worker management as a gRPC service.
// This enables the orchestrator to communicate with the BuildKit Manager
// as a separate microservice, allowing independent scaling and fault isolation.
//
// Phase 6 of microservices architecture: See issue #186.
type BuildKitManagerServiceServer interface {
	// RequestWorker acquires a BuildKit worker for the given build requirements.
	// The returned worker must be released when the build completes.
	RequestWorker(context.Context, *RequestWorkerRequest) (*RequestWorkerResponse, error)
	// ReleaseWorker returns a worker to the manager and records the build result.
	// This must be called when a build completes (regardless of outcome).
	ReleaseWorker(context.Context, *ReleaseWorkerRequest) (*ReleaseWorkerResponse, error)
	// GetStatus returns current state of all workers for observability.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetCapacity returns the total job capacity across all backends.
	GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error)
	// GetArchitectures returns a list of supported architectures.
	GetArchitectures(context.Context, *GetArchitecturesRequest) (*GetArchitecturesResponse, error)
	// Health returns the health status of the service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBuildKitManagerServiceServer()
}

// UnimplementedBuildKitManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildKitManagerServiceServer struct{}

func (UnimplementedBuildKitManagerServiceServer) RequestWorker(context.Context, *RequestWorkerRequest) (*RequestWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestWorker not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) ReleaseWorker(context.Context, *ReleaseWorkerRequest) (*ReleaseWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseWorker not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) GetArchitectures(context.Context, *GetArchitecturesRequest) (*GetArchitecturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArchitectures not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBuildKitManagerServiceServer) mustEmbedUnimplementedBuildKitManagerServiceServer() {
}
func (UnimplementedBuildKitManagerServiceServer) testEmbeddedByValue() {}

// UnsafeBuildKitManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildKitManagerServiceServer will
// result in compilation errors.
type UnsafeBuildKitManagerServiceServer interface {
	mustEmbedUnimplementedBuildKitManagerServiceServer()
}

func RegisterBuildKitManagerServiceServer(s grpc.ServiceRegistrar, srv BuildKitManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBuildKitManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildKitManagerService_ServiceDesc, srv)
}

func _BuildKitManagerService_RequestWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).RequestWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_RequestWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).RequestWorker(ctx, req.(*RequestWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildKitManagerService_ReleaseWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).ReleaseWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_ReleaseWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).ReleaseWorker(ctx, req.(*ReleaseWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildKitManagerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildKitManagerService_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildKitManagerService_GetArchitectures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchitecturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).GetArchitectures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_GetArchitectures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).GetArchitectures(ctx, req.(*GetArchitecturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildKitManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildKitManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildKitManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildKitManagerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildKitManagerService_ServiceDesc is the grpc.ServiceDesc for BuildKitManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildKitManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buildkit.manager.v1.BuildKitManagerService",
	HandlerType: (*BuildKitManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestWorker",
			Handler:    _BuildKitManagerService_RequestWorker_Handler,
		},
		{
			MethodName: "ReleaseWorker",
			Handler:    _BuildKitManagerService_ReleaseWorker_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BuildKitManagerService_GetStatus_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _BuildKitManagerService_GetCapacity_Handler,
		},
		{
			MethodName: "GetArchitectures",
			Handler:    _BuildKitManagerService_GetArchitectures_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BuildKitManagerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/service/buildkit/buildkit_manager.proto",
}
